org: adrianurbinamendoza
service: api-web-scraping

provider:
  name: aws
  runtime: python3.13
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::254780740814:role/LabRole

functions:
  scrape_table:
    handler: scrap_table.lambda_handler
    package:
      include:
        - ./**
    events:
      - http:
          path: /scrape/table
          method: get
          cors: true
          integration: lambda

resources:
  Resources:
    TablaWebScraping2:           # <-- nombre interno del recurso
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TablaWebScraping2   # <-- nuevo nombre de la tabla
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
